version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=your-root-password
    volumes:
      - mongo-data:/data/db

  recipes-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:your-root-password@mongo:27017/recipes_db?authSource=admin
    depends_on:
      - mongo

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_URI=mongodb://root:your-root-password@mongo:27017/recipes_db?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
