apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recipes-dary-project.fullname" . }}-mongodb-data
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass | default "default" }}
